name: Trigger rosbot-docker to build an image

on:
  push:
    branches:
      - "ros2"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: trigger the endpoint
        run: >
          curl -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}"
          https://api.github.com/repos/husarion/rosbot-docker/dispatches
          -d '{"event_type":"ros-package-update"}'